[package]
name = "transactioner"
authors = ["Dídac Sementé Fernández <didac.semente@gmail.com>"]
version = "1.0.0"
edition = "2018"
publish = false

[dependencies]
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
float-cmp = "0.9.0"
